- hosts: localhost
  tasks:
    - name: Use One Workspace
      dconf:
        key: /org/gnome/desktop/wm/preferences/num-workspaces
        value: 1
    - name: Disable Dynamic Workspaces in GNOME Shell
      dconf:
        key: /org/gnome/shell/overrides/dynamic-workspaces
        value: "false"
    - name: Disable Dynamic Workspaces in Mutter
      dconf:
        key: /org/gnome/mutter/dynamic-workspaces
        value: "false"
    - name: Use 24-hour clock
      dconf:
        key: /org/gnome/desktop/interface/clock-format
        value: "'24h'"
