- hosts: localhost
  tasks:
    - name: Install Builder
      flatpak:
        name:  https://flathub.org/repo/appstream/org.gnome.Builder.flatpakref
        method: system
        state: present
    - name: Install Steam
      flatpak:
        name:  https://flathub.org/repo/appstream/com.valvesoftware.Steam.flatpakref
        method: system
        state: present
    - name: Install the GIMP
      flatpak:
        name:  https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
        method: system
        state: present
    - name: Install Inkscape
      flatpak:
        name:  https://flathub.org/repo/appstream/org.inkscape.Inkscape.flatpakref
        method: system
        state: present
    - name: Install Meld
      flatpak:
        name:  https://flathub.org/repo/appstream/org.gnome.meld.flatpakref
        method: system
        state: present
    - name: Install Fragments
      flatpak:
        name:  https://flathub.org/repo/appstream/de.haeckerfelix.Fragments.flatpakref
        method: system
        state: present
    - name: Install GNOME Hex Editor
      flatpak:
        name:  https://flathub.org/repo/appstream/org.gnome.ghex.flatpakref
        method: system
        state: present
    - name: Install Dconf Editor
      flatpak:
        name:  https://flathub.org/repo/appstream/ca.desrt.dconf-editor.flatpakref
        method: system
        state: present
    - name: Install GNOME Videos
      flatpak:
        name: https://flathub.org/repo/appstream/org.gnome.Totem.flatpakref
        method: system
        state: present
    - name: Install GNOME Games
      flatpak:
        name: https://flathub.org/repo/appstream/org.gnome.Games.flatpakref
        method: system
        state: present
    - name: Install GNU Octave
      flatpak:
        name: https://flathub.org/repo/appstream/org.octave.Octave.flatpakref
        method: system
        state: present
    - name: Install LibreOffice
      flatpak:
        name: https://flathub.org/repo/appstream/org.libreoffice.LibreOffice.flatpakref
        method: system
        state: present
    - name: Install Fedora Media Writer
      flatpak:
        name: https://flathub.org/repo/appstream/org.fedoraproject.MediaWriter.flatpakref
        method: system
        state: present
    - name: Install UberWriter Markdown Editor
      flatpak:
        name: https://flathub.org/repo/appstream/de.wolfvollprecht.UberWriter.flatpakref
        method: system
        state: present
    - name: Disable DConf Editor Warning
      shell: dconf write /ca/desrt/dconf-editor/show-warning "false"
    - name: Interpret Caps Lock as Ctrl
      shell: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:ctrl_modifier']"
    - name: Show Seconds on the Desktop Clock
      shell: dconf write /org/gnome/desktop/interface/clock-show-seconds "true"
    - name: Show Date on the Desktop Clock
      shell: dconf write /org/gnome/desktop/interface/clock-show-date "true"
    - name: Use Natural Scrolling
      shell: dconf write /org/gnome/desktop/peripherals/mouse/natural-scroll "true"
    - name: Use LCD-Style Antialiasing
      shell: dconf write /org/gnome/settings-daemon/plugins/xsettings "'rgba'"
    - name: Automatically Remove Old Temporary Files
      shell: dconf write /org/gnome/desktop/privacy/remove-old-temp-files "true"
    - name: Automatically Remove Old Trash Files
      shell: dconf write /org/gnome/desktop/privacy/remove-old-trash-files "true"
    - name: Assume GNOME Software Has Been Used Before
      shell: dconf write /org/gnome/software/first-run "false"
    - name: Disable All GNOME Extensions
      shell: dconf write /org/gnome/shell/enabled-extensions "@as []"
    - name: Configure F12 to Reset and Clear the Terminal
      shell: dconf write /org/gnome/terminal/legacy/keybindings/reset-and-clear "'F12'"
    - name: Disable Lock Screen Notifications
      shell: dconf write /org/gnome/desktop/notifications/show-in-lock-screen "false"
    - name: Cap History Retention Time
      shell: dconf write /org/gnome/desktop/privacy/recent-files-max-age 30
    - name: Read Default Terminal Profile
      shell: "gsettings get org.gnome.Terminal.ProfilesList default | tr --delete \"'\""
      register: terminal_default_profile
      tags: register
    - name: Terminal - Unlimited Scrollback
      shell: dconf write /org/gnome/terminal/legacy/profiles:/:{{ terminal_default_profile.stdout }}/scrollback-unlimited "true"
      when: not ansible_check_mode
    - name: Create Environment Configuration Directory
      file:
        path: ~/.config/environment.d/
        state: directory
    - name: Create Autostart Configuration Directory
      file:
        path: ~/.config/autostart/
        state: directory
    - name: Disable GNOME Keyring Autostart
      copy:
        dest: "~/.config/autostart/gnome-keyring-ssh.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=SSH Key Agent
          Exec=/usr/bin/true
          Hidden=true
    - name: Configure SSH to Use the GPG Agent
      copy:
        dest: "~/.config/environment.d/50-ssh-agent.conf"
        content: |
          SSH_AGENT_PID=
          SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh
    - name: Create systemd User Session Directory
      file:
        path: ~/.config/systemd/user/
        state: directory
    - name: Create a GPG Agent Service
      copy:
        dest: "~/.config/systemd/user/gpg-agent.service"
        content: |
          [Service]
          ExecStart=/usr/bin/gpg-agent --supervised --enable-ssh-support
          ExecReload=/usr/bin/gpgconf --reload gpg-agent
    - name: Create a GPG Agent Socket
      copy:
        dest: "~/.config/systemd/user/gpg-agent.socket"
        content: |
          [Socket]
          ListenStream=%t/gnupg/S.gpg-agent
          FileDescriptorName=std
          SocketMode=0600
          DirectoryMode=0700
          
          [Install]
          WantedBy=sockets.target
    - name: Create a GPG SSH Agent Socket
      copy:
        dest: "~/.config/systemd/user/gpg-agent-ssh.socket"
        content: |
          [Socket]
          ListenStream=%t/gnupg/S.gpg-agent.ssh
          FileDescriptorName=ssh
          Service=gpg-agent.service
          SocketMode=0600
          DirectoryMode=0700
          
          [Install]
          WantedBy=sockets.target
    - name: Reload user-level systemd configuration
      shell: systemctl --user daemon-reload
    - name: Enable and Start the GPG Agent Socket
      systemd:
        name: gpg-agent.socket
        state: started
        enabled: yes
        scope: user
    - name: Enable and Start the GPG SSH Agent Socket
      systemd:
        name: gpg-agent-ssh.socket
        state: started
        enabled: yes
        scope: user
