- hosts: localhost
  tasks:
    - name: Install Builder
      become: yes
      package:
        name: gnome-builder
        state: present
    - name: Install GIMP
      become: yes
      package:
        name: gimp
        state: present
    - name: Install Inkscape
      become: yes
      package:
        name: inkscape
        state: present
    - name: Install htop
      become: yes
      package:
        name: htop
        state: present
    - name: Install iotop
      become: yes
      package:
        name: iotop
        state: present
    - name: Install MariaDB
      become: yes
      package:
        name: mariadb
        state: present
    - name: Install Meld
      become: yes
      package:
        name: meld
        state: present
    - name: Install GNU Nano
      become: yes
      package:
        name: nano
        state: present
    - name: Install PHP with CLI
      become: yes
      package:
        name: php-cli
        state: present
    - name: Install Powertop
      become: yes
      package:
        name: powertop
        state: present
    - name: Install Tor
      become: yes
      package:
        name: tor
        state: present
    - name: Install Unbound
      become: yes
      package:
        name: unbound
        state: present
    - name: Install Wireshark
      become: yes
      package:
        name: wireshark
        state: present
    - name: Install Transmission
      become: yes
      package:
        name: transmission
        state: present
    - name: Install GNOME System Log
      become: yes
      package:
        name: gnome-system-log
        state: present
    - name: Install FATSort
      become: yes
      package:
        name: fatsort
        state: present
    - name: Install Unbound DNS Client
      become: yes
      package:
        name: unbound
        state: present
    - name: Install Nmap Network Scanner
      become: yes
      package:
        name: nmap
        state: present
    - name: Install Password Manager
      become: yes
      package:
        name: pass
        state: present
    - name: Install GHex Hex Editor
      become: yes
      package:
        name: ghex
        state: present
    - name: Install Composer for PHP
      become: yes
      package:
        name: composer
        state: present
    - name: Install Network Configuration for libvirt Virtual Machines
      become: yes
      package:
        name: libvirt-daemon-config-network
        state: present
    - name: Install GNOME Shell Support for Chrome
      become: yes
      package:
        name: chrome-gnome-shell
        state: present
    - name: Install PCSC Smart Card Drivers
      become: yes
      package:
        name: pcsc-lite
        state: present
    - name: Install Python VirtualEnv Tools for Isolated Environments
      become: yes
      package:
        name: python3-virtualenv
        state: present
    - name: Install System Utilities for Python (for Ansible)
      become: yes
      package:
        name: python3-psutil
        state: present
    - name: Disable DConf Editor Warning
      dconf:
        key: /ca/desrt/dconf-editor/show-warning
        value: "false"
    - name: Interpret Caps Lock as Ctrl
      dconf:
        key: /org/gnome/desktop/input-sources/xkb-options
        value: "['caps:ctrl_modifier']"
    - name: Show Seconds on the Desktop Clock
      dconf:
        key: /org/gnome/desktop/interface/clock-show-seconds
        value: "true"
    - name: Show Date on the Desktop Clock
      dconf:
        key: /org/gnome/desktop/interface/clock-show-date
        value: "true"
    - name: Use Natural Scrolling
      dconf:
        key: /org/gnome/desktop/peripherals/mouse/natural-scroll
        value: "true"
    - name: Use LCD-Style Antialiasing
      dconf:
        key: /org/gnome/settings-daemon/plugins/xsettings
        value: "'rgba'"
    - name: Automatically Remove Old Temporary Files
      dconf:
        key: /org/gnome/desktop/privacy/remove-old-temp-files
        value: "true"
    - name: Automatically Remove Old Trash Files
      dconf:
        key: /org/gnome/desktop/privacy/remove-old-trash-files
        value: "true"
    - name: Assume GNOME Software Has Been Used Before
      dconf:
        key: /org/gnome/software/first-run
        value: "false"
    - name: Disable All GNOME Extensions
      dconf:
        key: /org/gnome/shell/enabled-extensions
        value: "@as []"
    - name: Configure F12 to Reset and Clear the Terminal
      dconf:
        key: /org/gnome/terminal/legacy/keybindings/reset-and-clear
        value: "'F12'"
    - name: Read Default Terminal Profile
      shell: "gsettings get org.gnome.Terminal.ProfilesList default | tr --delete \"'\""
      register: terminal_default_profile
      tags: register
    - name: Terminal - Unlimited Scrollback
      dconf:
        key: /org/gnome/terminal/legacy/profiles:/:{{ terminal_default_profile.stdout }}/scrollback-unlimited
        value: "true"
    - name: Create Environment Configuration Directory
      file:
        path: ~/.config/environment.d/
        state: directory
    - name: Create Autostart Configuration Directory
      file:
        path: ~/.config/autostart/
        state: directory
    - name: Disable GNOME Keyring Autostart
      copy:
        dest: "~/.config/autostart/gnome-keyring-ssh.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=SSH Key Agent
          Exec=/usr/bin/true
          Hidden=true
    - name: Configure SSH to Use the GPG Agent
      copy:
        dest: "~/.config/environment.d/50-ssh-agent.conf"
        content: |
          SSH_AGENT_PID=
          SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh
    - name: Create systemd User Session Directory
      file:
        path: ~/.config/systemd/user/
        state: directory
    - name: Create a GPG Agent Service
      copy:
        dest: "~/.config/systemd/user/gpg-agent.service"
        content: |
          [Service]
          ExecStart=/usr/bin/gpg-agent --supervised --enable-ssh-support
          ExecReload=/usr/bin/gpgconf --reload gpg-agent
    - name: Create a GPG Agent Socket
      copy:
        dest: "~/.config/systemd/user/gpg-agent.socket"
        content: |
          [Socket]
          ListenStream=%t/gnupg/S.gpg-agent
          FileDescriptorName=std
          SocketMode=0600
          DirectoryMode=0700
          
          [Install]
          WantedBy=sockets.target
    - name: Create a GPG SSH Agent Socket
      copy:
        dest: "~/.config/systemd/user/gpg-agent-ssh.socket"
        content: |
          [Socket]
          ListenStream=%t/gnupg/S.gpg-agent.ssh
          FileDescriptorName=ssh
          Service=gpg-agent.service
          SocketMode=0600
          DirectoryMode=0700
          
          [Install]
          WantedBy=sockets.target
    - name: Enable and Start the GPG Agent Socket
      systemd:
        name: gpg-agent.socket
        state: started
        enabled: yes
        scope: user
    - name: Enable and Start the GPG SSH Agent Socket
      systemd:
        name: gpg-agent-ssh.socket
        state: started
        enabled: yes
        scope: user
